### ISSUE TITLE
Compatibility with Acer A515-51G-5621 (2017) i5 7200u dGPU: 940mx

### ISSUE THREAD

**Issue by Nparte777** [AnshulRaghav/Acer-Big-Sur-Hackintosh#1]
Would like to know if this repo is viable for the above given Configuration

**Comment by AnshulRaghav** [comment]
> Would like to know if this repo is viable for the above given Configuration

Yes. Also generate SMBIOS data for your laptop and replace mine with yours.You can find more details about this in the [TechNolli's](https://www.youtube.com/watch?v=jqg7MX3FS7M) video tutorial.
